CREATE TABLE ESTADOS_PRESTADORES (
  ID NUMBER(22,0) not null,
  NOMBRE VARCHAR2(255) not null,
  COMUNA_ID NUMBER(22,0) not null
);

CREATE TABLE MODALIDADES (
  ID  NUMBER(22,0) not null,
  NOMBRE VARCHAR2(255) not null
);

CREATE TABLE TIPO_COMUNAS (
  ID  NUMBER(22,0) not null,
  TIPO VARCHAR2(255) not null
);

CREATE TABLE COMUNAS (
  ID  NUMBER(22,0) not null,
  NOMBRE VARCHAR2(255) not null,
  TIPO_COMUNA_ID NUMBER(22,0) not null
);

CREATE TABLE BARRIOS(
  ID  NUMBER(22,0) not null,
  NOMBRE VARCHAR2(255) not null,
  COMUNA_ID NUMBER(22,0) not null
);

CREATE TABLE PRESTADORES(
  ID  NUMBER(22,0) not null,
  NOMBRE VARCHAR2(255) not null,
  FECHA_CONTRATACION DATE NOT NULL,
  VALOR_CONTRATO NUMBER(19,2) NOT NULL,
  ESTADO_ID  NUMBER(22,0) not null
);

CREATE TABLE SEDES(
  ID  NUMBER(22,0) not null,
  SEDE  NUMBER(22,0) not null,
  TELEFONO  NUMBER(22,0) not null,
  DIRECCION   NUMBER(22,0) not null,
  CUPOS_DISPUESTOS  NUMBER(22,0) not null,
  BARRIO_ID  NUMBER(22,0) not null,
  MODALIDAD_ID  NUMBER(22,0) not null,
  PRESTADOR_ID  NUMBER(22,0) not null
);

ALTER TABLE SEDES ADD PRIMARY KEY (ID) ENABLE;
ALTER TABLE BARRIOS ADD PRIMARY KEY (ID) ENABLE;
ALTER TABLE MODALIDADES ADD PRIMARY KEY (ID) ENABLE;
ALTER TABLE COMUNAS ADD PRIMARY KEY (ID) ENABLE;
ALTER TABLE TIPO_COMUNAS ADD PRIMARY KEY (ID) ENABLE;
ALTER TABLE PRESTADORES ADD PRIMARY KEY (ID) ENABLE;
ALTER TABLE ESTADOS_PRESTADORES ADD PRIMARY KEY (ID) ENABLE;

ALTER TABLE PRESTADORES ADD CONSTRAINT "PRESTADORES_FK" FOREIGN KEY (ESTADO_ID)
REFERENCES ESTADOS_PRESTADORES (ID) ENABLE;

ALTER TABLE COMUNAS ADD CONSTRAINT "TIPO_COMUNAS_FK" FOREIGN KEY (TIPO_COMUNA_ID)
REFERENCES TIPO_COMUNAS (ID) ENABLE;

ALTER TABLE BARRIOS ADD CONSTRAINT "BARRIOS_COMUNAS_FK" FOREIGN KEY (COMUNA_ID)
REFERENCES COMUNAS (ID) ENABLE;

ALTER TABLE SEDES ADD CONSTRAINT "PRESTADORES_SEDES_FK" FOREIGN KEY (PRESTADOR_ID)
REFERENCES PRESTADORES (ID) ENABLE;

ALTER TABLE SEDES ADD CONSTRAINT "MODALIDAD_FK" FOREIGN KEY (MODALIDAD_ID)
REFERENCES MODALIDADES (ID) ENABLE;

ALTER TABLE SEDES ADD CONSTRAINT "BARRIO_FK" FOREIGN KEY (BARRIO_ID)
REFERENCES BARRIOS (ID) ENABLE;

