ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

create tablespace mid_term
datafile 'any.dbf' size 20M;


ALTER profile parcial limit
FAILED_LOGIN_ATTEMPTS 19
IDLE_TIME 20;

CREATE USER JHERRERA
IDENTIFIED BY Developer123
DEFAULT TABLESPACE mid_term
QUOTA UNLIMITED ON mid_term;

ALTER USER JHERRERA PROFILE parcial;

CREATE USER ANYUSER
IDENTIFIED BY Developer123
DEFAULT TABLESPACE mid_term;

ALTER USER ANYUSER PROFILE parcial;

CREATE ROLE MINI_DBA;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO MINI_DBA;

CREATE ROLE STUDENT;
GRANT CREATE SESSION TO STUDENT;

GRANT MINI_DBA TO JHERRERA;